name: Deploy to EC2

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}  # EC2のホスト名（IPアドレスやDNS）
        username: ${{ vars.EC2_USER }}  # EC2のユーザー名（通常はec2-user）
        key: ${{ secrets.EC2_PRIVATE_KEY }}  # シークレットに設定した秘密鍵
        source: "./*"  # コピーするファイル
        target: "/home/ubuntu/web/myresume-website"  # EC2上のウェブサーバーのドキュメントルート

    - name: Restart web server
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > key.pem  # 秘密鍵をファイルに保存
        chmod 400 key.pem  # 適切な権限を設定
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "sudo systemctl restart nginx"  # Nginxを再起動
